### ISSUE TITLE
Use ttfautohint from dev repo?

### ISSUE THREAD

**Issue by sungsit** [fontuni/boonjot#10]
@davelab6, should I use ttfautohint from dev repo http://repo.or.cz/w/ttfautohint.git since it supports Thai script?

From my quick test, I can't compile it with QT on Archlinux but the command line mode is fine. It looks more promising than hint Thai as symbol font.

**Comment by davelab6** [comment]
Yes, totally! QT is only needed for the UI; and the UI is just a convenient
way to set up the arguments to the command line tool.

What was the compilation error?

cc @lzwemberg

**Comment by sungsit** [comment]
I can't reproduce compilation error right now but it's related to doc & QT, just use `--without-*` flags when run configure then it's fine. Homebrew with `brew install ttfautohint --HEAD` is also fine.
